version: '3.9'
services:
  bynder-lottery-service:
    image: bynder-lottery-via:0.1.0-SNAPSHOT
    ports:
      - "28080:8080"
  bynder-lottery-timescaledb:
    container_name: bynder-lottery-timescaledb
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: titkos
    ports:
      - "25432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql